### ISSUE TITLE
查看技能指令大小写不对

### ISSUE THREAD

**Issue by shixiaoxiao233** [handy-git/McMmoView#3]
mcmmo版本2.2.012，插件1.0.7，获取技能信息指令为大写，有些时候打开菜单会有好几秒的延迟，控制台无报错
![{960FC508-1130-4dfc-A0DA-B54B0240CA41}](https://github.com/handy-git/McMmoView/assets/84579964/b04aaead-6414-4cb7-b0cb-e828ec241b2d)

**Comment by handy-git** [comment]
我测试从gui中打开使用大写是没影响的

**Comment by shixiaoxiao233** [comment]
服务器版本leaves-1.20.6，这边试必须要用tab切成小写才行

**Comment by handy-git** [comment]
> 服务器版本leaves-1.20.6，这边试必须要用tab切成小写才行

使用1.0.8 默认调整为执行小写了
